### ISSUE TITLE
Price and VAT

### ISSUE THREAD

**Issue by fnielsen** [workshop-oc/workshop-oc.github.io#2]
There seems to be an issue with the price. https://github.com/workshop-oc/workshop-oc.github.io/commit/7d8f6b946409155361506f36c487bbcdd4073a27#diff-eacf331f0ffc35d4b482f1d15a887d3bR218 states that the price was €100, while one email claimed that price was not including VAT. See also https://europa.eu/youreurope/citizens/consumers/shopping/pricing-payments/index_it.htm

**Comment by marilenadaquino** [comment]
Dear Finn,
as mentioned in a private email, we had to add the VAT because of bureaucratic reasons. Since the organisers are going to pay the VAT instead of you, we had to raise the fee. 

Considering the fee includes three lunches, six coffee breaks, a social dinner, and a sightseeing tour, the amount of money requested seems reasonable for covering all such expenses and give you all a great experience during the workshop.

I hope you agree. Apologies again for the misunderstanding.
Best,
MD
